/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiGetServerInfoGetRequest
 */
export interface ApiGetServerInfoGetRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiGetServerInfoGetRequest
     */
    serverHost: string;
}

/**
 * Check if a given object implements the ApiGetServerInfoGetRequest interface.
 */
export function instanceOfApiGetServerInfoGetRequest(value: object): value is ApiGetServerInfoGetRequest {
    if (!('serverHost' in value) || value['serverHost'] === undefined) return false;
    return true;
}

export function ApiGetServerInfoGetRequestFromJSON(json: any): ApiGetServerInfoGetRequest {
    return ApiGetServerInfoGetRequestFromJSONTyped(json, false);
}

export function ApiGetServerInfoGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiGetServerInfoGetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serverHost': json['ServerHost'],
    };
}

export function ApiGetServerInfoGetRequestToJSON(json: any): ApiGetServerInfoGetRequest {
    return ApiGetServerInfoGetRequestToJSONTyped(json, false);
}

export function ApiGetServerInfoGetRequestToJSONTyped(value?: ApiGetServerInfoGetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ServerHost': value['serverHost'],
    };
}

