/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiGetServerInfoGet200Response
 */
export interface ApiGetServerInfoGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiGetServerInfoGet200Response
     */
    rtt: string;
    /**
     * 
     * @type {number}
     * @memberof ApiGetServerInfoGet200Response
     */
    clients: number;
    /**
     * 
     * @type {number}
     * @memberof ApiGetServerInfoGet200Response
     */
    maxClients: number;
}

/**
 * Check if a given object implements the ApiGetServerInfoGet200Response interface.
 */
export function instanceOfApiGetServerInfoGet200Response(value: object): value is ApiGetServerInfoGet200Response {
    if (!('rtt' in value) || value['rtt'] === undefined) return false;
    if (!('clients' in value) || value['clients'] === undefined) return false;
    if (!('maxClients' in value) || value['maxClients'] === undefined) return false;
    return true;
}

export function ApiGetServerInfoGet200ResponseFromJSON(json: any): ApiGetServerInfoGet200Response {
    return ApiGetServerInfoGet200ResponseFromJSONTyped(json, false);
}

export function ApiGetServerInfoGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiGetServerInfoGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'rtt': json['Rtt'],
        'clients': json['Clients'],
        'maxClients': json['MaxClients'],
    };
}

export function ApiGetServerInfoGet200ResponseToJSON(json: any): ApiGetServerInfoGet200Response {
    return ApiGetServerInfoGet200ResponseToJSONTyped(json, false);
}

export function ApiGetServerInfoGet200ResponseToJSONTyped(value?: ApiGetServerInfoGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Rtt': value['rtt'],
        'Clients': value['clients'],
        'MaxClients': value['maxClients'],
    };
}

