/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiServerInfoGetRequest
 */
export interface ApiServerInfoGetRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiServerInfoGetRequest
     */
    serverHost: string;
}

/**
 * Check if a given object implements the ApiServerInfoGetRequest interface.
 */
export function instanceOfApiServerInfoGetRequest(value: object): value is ApiServerInfoGetRequest {
    if (!('serverHost' in value) || value['serverHost'] === undefined) return false;
    return true;
}

export function ApiServerInfoGetRequestFromJSON(json: any): ApiServerInfoGetRequest {
    return ApiServerInfoGetRequestFromJSONTyped(json, false);
}

export function ApiServerInfoGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiServerInfoGetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serverHost': json['ServerHost'],
    };
}

export function ApiServerInfoGetRequestToJSON(json: any): ApiServerInfoGetRequest {
    return ApiServerInfoGetRequestToJSONTyped(json, false);
}

export function ApiServerInfoGetRequestToJSONTyped(value?: ApiServerInfoGetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ServerHost': value['serverHost'],
    };
}

