/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamePathGet
 */
export interface GamePathGet {
    /**
     * 
     * @type {string}
     * @memberof GamePathGet
     */
    gamePath: string;
}

/**
 * Check if a given object implements the GamePathGet interface.
 */
export function instanceOfGamePathGet(value: object): value is GamePathGet {
    if (!('gamePath' in value) || value['gamePath'] === undefined) return false;
    return true;
}

export function GamePathGetFromJSON(json: any): GamePathGet {
    return GamePathGetFromJSONTyped(json, false);
}

export function GamePathGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamePathGet {
    if (json == null) {
        return json;
    }
    return {
        
        'gamePath': json['GamePath'],
    };
}

export function GamePathGetToJSON(json: any): GamePathGet {
    return GamePathGetToJSONTyped(json, false);
}

export function GamePathGetToJSONTyped(value?: GamePathGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'GamePath': value['gamePath'],
    };
}

