/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGamePathResp
 */
export interface GetGamePathResp {
    /**
     * 
     * @type {string}
     * @memberof GetGamePathResp
     */
    gamePath: string;
}

/**
 * Check if a given object implements the GetGamePathResp interface.
 */
export function instanceOfGetGamePathResp(value: object): value is GetGamePathResp {
    if (!('gamePath' in value) || value['gamePath'] === undefined) return false;
    return true;
}

export function GetGamePathRespFromJSON(json: any): GetGamePathResp {
    return GetGamePathRespFromJSONTyped(json, false);
}

export function GetGamePathRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGamePathResp {
    if (json == null) {
        return json;
    }
    return {
        
        'gamePath': json['GamePath'],
    };
}

export function GetGamePathRespToJSON(json: any): GetGamePathResp {
    return GetGamePathRespToJSONTyped(json, false);
}

export function GetGamePathRespToJSONTyped(value?: GetGamePathResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'GamePath': value['gamePath'],
    };
}

