/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetServerInfoReq
 */
export interface GetServerInfoReq {
    /**
     * 
     * @type {string}
     * @memberof GetServerInfoReq
     */
    serverHost: string;
}

/**
 * Check if a given object implements the GetServerInfoReq interface.
 */
export function instanceOfGetServerInfoReq(value: object): value is GetServerInfoReq {
    if (!('serverHost' in value) || value['serverHost'] === undefined) return false;
    return true;
}

export function GetServerInfoReqFromJSON(json: any): GetServerInfoReq {
    return GetServerInfoReqFromJSONTyped(json, false);
}

export function GetServerInfoReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServerInfoReq {
    if (json == null) {
        return json;
    }
    return {
        
        'serverHost': json['ServerHost'],
    };
}

export function GetServerInfoReqToJSON(json: any): GetServerInfoReq {
    return GetServerInfoReqToJSONTyped(json, false);
}

export function GetServerInfoReqToJSONTyped(value?: GetServerInfoReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ServerHost': value['serverHost'],
    };
}

