/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetServerInfoResp
 */
export interface GetServerInfoResp {
    /**
     * 
     * @type {string}
     * @memberof GetServerInfoResp
     */
    clients: string;
    /**
     * 
     * @type {string}
     * @memberof GetServerInfoResp
     */
    maxClients: string;
}

/**
 * Check if a given object implements the GetServerInfoResp interface.
 */
export function instanceOfGetServerInfoResp(value: object): value is GetServerInfoResp {
    if (!('clients' in value) || value['clients'] === undefined) return false;
    if (!('maxClients' in value) || value['maxClients'] === undefined) return false;
    return true;
}

export function GetServerInfoRespFromJSON(json: any): GetServerInfoResp {
    return GetServerInfoRespFromJSONTyped(json, false);
}

export function GetServerInfoRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServerInfoResp {
    if (json == null) {
        return json;
    }
    return {
        
        'clients': json['Clients'],
        'maxClients': json['MaxClients'],
    };
}

export function GetServerInfoRespToJSON(json: any): GetServerInfoResp {
    return GetServerInfoRespToJSONTyped(json, false);
}

export function GetServerInfoRespToJSONTyped(value?: GetServerInfoResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Clients': value['clients'],
        'MaxClients': value['maxClients'],
    };
}

