/*
 * 默认模块
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiModels

type ApiGetServerInfoGet200Response struct {

	Rtt string `json:"Rtt"`

	Clients float32 `json:"Clients"`

	MaxClients float32 `json:"MaxClients"`
}
