/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GamePathGet,
} from '../models/index';
import {
    GamePathGetFromJSON,
    GamePathGetToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 获取游戏存储路径
     * 获取游戏路径
     */
    async apiGetGamePathGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GamePathGet>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/GetGamePath`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GamePathGetFromJSON(jsonValue));
    }

    /**
     * 获取游戏存储路径
     * 获取游戏路径
     */
    async apiGetGamePathGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GamePathGet> {
        const response = await this.apiGetGamePathGetRaw(initOverrides);
        return await response.value();
    }

}
