/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiGetServerInfoGet200Response,
  GetGamePathResp,
} from '../models/index';
import {
    ApiGetServerInfoGet200ResponseFromJSON,
    ApiGetServerInfoGet200ResponseToJSON,
    GetGamePathRespFromJSON,
    GetGamePathRespToJSON,
} from '../models/index';

export interface ApiGetServerInfoGetRequest {
    serverHost?: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 获取游戏存储路径
     * 获取游戏路径
     */
    async apiGetGamePathGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGamePathResp>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/GetGamePath`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGamePathRespFromJSON(jsonValue));
    }

    /**
     * 获取游戏存储路径
     * 获取游戏路径
     */
    async apiGetGamePathGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGamePathResp> {
        const response = await this.apiGetGamePathGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * 
     * 获取服务器信息
     */
    async apiGetServerInfoGetRaw(requestParameters: ApiGetServerInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiGetServerInfoGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['serverHost'] != null) {
            queryParameters['ServerHost'] = requestParameters['serverHost'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/GetServerInfo`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiGetServerInfoGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * 获取服务器信息
     */
    async apiGetServerInfoGet(requestParameters: ApiGetServerInfoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiGetServerInfoGet200Response> {
        const response = await this.apiGetServerInfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
