/* tslint:disable */
/* eslint-disable */
/**
 * DHC AC Installer API
 * DHC AC Installer 前后端 API 接口规范
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  ApiGetServerInfoGet200Response,
  AppStateResp,
  CreateInstallationReq,
  CreateInstallationResp,
  GetDiskInfoResp,
  GetGamePathResp,
  InstallationProgressResp,
  PrecheckCmResp,
  PrecheckDlcResp,
  PrecheckResourcesResp,
  UpsertServerDisclaimerReq,
} from '../models/index';
import {
  ApiGetServerInfoGet200ResponseFromJSON,
  AppStateRespFromJSON,
  CreateInstallationReqToJSON,
  CreateInstallationRespFromJSON,
  GetDiskInfoRespFromJSON,
  GetGamePathRespFromJSON,
  InstallationProgressRespFromJSON,
  PrecheckCmRespFromJSON,
  PrecheckDlcRespFromJSON,
  PrecheckResourcesRespFromJSON,
  UpsertServerDisclaimerReqToJSON,
} from '../models/index';

export interface ApiGetServerInfoGetRequest {
    serverHost?: string;
}

export interface ApiGetDiskInfoGetRequest {
    drive?: string;
}

export interface ApiCreateInstallationRequest {
    body: CreateInstallationReq;
}

export interface ApiGetInstallationProgressRequest {
    installId: string;
    category?: string;
}

export interface ApiUpsertServerDisclaimerRequest {
    body: UpsertServerDisclaimerReq;
}

/**
 * DHC AC Installer API
 */
export class DefaultApi extends runtime.BaseAPI {

    // ── System ──

    async apiGetGamePathGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGamePathResp>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        const response = await this.request({
            path: `/api/GetGamePath`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => GetGamePathRespFromJSON(jsonValue));
    }

    async apiGetGamePathGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGamePathResp> {
        const response = await this.apiGetGamePathGetRaw(initOverrides);
        return await response.value();
    }

    async apiGetDiskInfoGetRaw(requestParameters: ApiGetDiskInfoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDiskInfoResp>> {
        const queryParameters: any = {};
        if (requestParameters['drive'] != null) {
            queryParameters['drive'] = requestParameters['drive'];
        }
        const headerParameters: runtime.HTTPHeaders = {};
        const response = await this.request({
            path: `/api/GetDiskInfo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => GetDiskInfoRespFromJSON(jsonValue));
    }

    async apiGetDiskInfoGet(requestParameters: ApiGetDiskInfoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDiskInfoResp> {
        const response = await this.apiGetDiskInfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    async apiGetServerInfoGetRaw(requestParameters: ApiGetServerInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiGetServerInfoGet200Response>> {
        const queryParameters: any = {};
        if (requestParameters['serverHost'] != null) {
            queryParameters['ServerHost'] = requestParameters['serverHost'];
        }
        const headerParameters: runtime.HTTPHeaders = {};
        const response = await this.request({
            path: `/api/GetServerInfo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => ApiGetServerInfoGet200ResponseFromJSON(jsonValue));
    }

    async apiGetServerInfoGet(requestParameters: ApiGetServerInfoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiGetServerInfoGet200Response> {
        const response = await this.apiGetServerInfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    // ── Installation ──

    async apiCreateInstallationRaw(requestParameters: ApiCreateInstallationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateInstallationResp>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/api/installations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInstallationReqToJSON(requestParameters['body']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => CreateInstallationRespFromJSON(jsonValue));
    }

    async apiCreateInstallation(requestParameters: ApiCreateInstallationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateInstallationResp> {
        const response = await this.apiCreateInstallationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    async apiGetInstallationProgressRaw(requestParameters: ApiGetInstallationProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstallationProgressResp>> {
        if (requestParameters['installId'] == null) {
            throw new runtime.RequiredError('installId', 'Required parameter installId was null or undefined.');
        }
        const queryParameters: any = {};
        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }
        const headerParameters: runtime.HTTPHeaders = {};
        const response = await this.request({
            path: `/api/installations/${encodeURIComponent(requestParameters['installId'])}/progress`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => InstallationProgressRespFromJSON(jsonValue));
    }

    async apiGetInstallationProgress(requestParameters: ApiGetInstallationProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstallationProgressResp> {
        const response = await this.apiGetInstallationProgressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    // ── Precheck ──

    async apiPrecheckResourcesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrecheckResourcesResp>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        const response = await this.request({
            path: `/api/demo/precheck/resources`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => PrecheckResourcesRespFromJSON(jsonValue));
    }

    async apiPrecheckResources(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrecheckResourcesResp> {
        const response = await this.apiPrecheckResourcesRaw(initOverrides);
        return await response.value();
    }

    async apiPrecheckDlcCarpackRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrecheckDlcResp>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        const response = await this.request({
            path: `/api/demo/precheck/dlc-carpack`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => PrecheckDlcRespFromJSON(jsonValue));
    }

    async apiPrecheckDlcCarpack(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrecheckDlcResp> {
        const response = await this.apiPrecheckDlcCarpackRaw(initOverrides);
        return await response.value();
    }

    async apiPrecheckCmRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrecheckCmResp>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        const response = await this.request({
            path: `/api/demo/precheck/cm`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => PrecheckCmRespFromJSON(jsonValue));
    }

    async apiPrecheckCm(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrecheckCmResp> {
        const response = await this.apiPrecheckCmRaw(initOverrides);
        return await response.value();
    }

    // ── AppState ──

    async apiGetAppStateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppStateResp>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        const response = await this.request({
            path: `/api/AppState`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => AppStateRespFromJSON(jsonValue));
    }

    async apiGetAppState(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppStateResp> {
        const response = await this.apiGetAppStateRaw(initOverrides);
        return await response.value();
    }

    async apiUpsertServerDisclaimerRaw(requestParameters: ApiUpsertServerDisclaimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/api/AppState/ServerDisclaimer`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpsertServerDisclaimerReqToJSON(requestParameters['body']),
        }, initOverrides);
        return new runtime.VoidApiResponse(response);
    }

    async apiUpsertServerDisclaimer(requestParameters: ApiUpsertServerDisclaimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiUpsertServerDisclaimerRaw(requestParameters, initOverrides);
    }
}
